In [2]:
#Q1
'''Ordinal encoding assigns unique integers to categories based on their order, while label encoding assigns unique integers without considering any 
order. Use ordinal encoding when the categories have a meaningful sequence (e.g., 'Low', 'Medium', 'High'). Use label encoding when there is no 
intrinsic order among categories (e.g., 'Red', 'Blue', 'Green').'''

"Ordinal encoding assigns unique integers to categories based on their order, while label encoding assigns unique integers without considering any \norder. Use ordinal encoding when the categories have a meaningful sequence (e.g., 'Low', 'Medium', 'High'). Use label encoding when there is no \nintrinsic order among categories (e.g., 'Red', 'Blue', 'Green')."

In [3]:
#Q2
'''Target Guided Ordinal Encoding assigns ordinal values to categories based on the mean of the target variable. Categories with higher means receive 
higher ordinal values. This technique is useful when there's a strong relationship between the categorical feature and the target variable.

Example:
In a project predicting house prices, you have a 'Neighborhood' feature. Calculate the mean house price for each neighborhood and encode them based on 
these means. This ensures neighborhoods with higher average prices get higher ordinal values, leveraging the relationship between neighborhood and 
house price for better predictions.'''

"Target Guided Ordinal Encoding assigns ordinal values to categories based on the mean of the target variable. Categories with higher means receive \nhigher ordinal values. This technique is useful when there's a strong relationship between the categorical feature and the target variable.\n\nExample:\nIn a project predicting house prices, you have a 'Neighborhood' feature. Calculate the mean house price for each neighborhood and encode them based on \nthese means. This ensures neighborhoods with higher average prices get higher ordinal values, leveraging the relationship between neighborhood and \nhouse price for better predictions."

In [4]:

#Q3

'''Covariance measures the degree to which two variables change together. It is important in statistical analysis for understanding the relationship 
between variables. A positive covariance indicates that variables increase together, while a negative covariance indicates that one increases as the
other decreases. Covariance is calculated by taking the average of the product of the deviations of each pair of data points from their respective 
means.'''

'Covariance measures the degree to which two variables change together. It is important in statistical analysis for understanding the relationship \nbetween variables. A positive covariance indicates that variables increase together, while a negative covariance indicates that one increases as the\nother decreases. Covariance is calculated by taking the average of the product of the deviations of each pair of data points from their respective \nmeans.'

In [5]:
#Q4
from sklearn.preprocessing import LabelEncoder
data = {
    'Color': ['red', 'green', 'blue'],
    'Size': ['small', 'medium', 'large'],
    'Material': ['wood', 'metal', 'plastic']
}

encoder = LabelEncoder()

data["encoded_color"] = encoder.fit_transform(data["Color"] )
data["encoded_Size"] = encoder.fit_transform(data["Size"] )
data["encoded_Material"] = encoder.fit_transform(data["Material"] )

print(data)

{'Color': ['red', 'green', 'blue'], 'Size': ['small', 'medium', 'large'], 'Material': ['wood', 'metal', 'plastic'], 'encoded_color': array([2, 1, 0], dtype=int64), 'encoded_Size': array([2, 1, 0], dtype=int64), 'encoded_Material': array([2, 0, 1], dtype=int64)}

In [6]:
#Q5
import numpy as np
import pandas as pd

data = {
    'Age': [25, 32, 47, 51, 62],
    'Income': [50000, 60000, 80000, 85000, 90000],
    'Education_Level': [12, 14, 16, 16, 18]
}
df = pd.DataFrame(data)

cov_matrix = np.cov(df.T)

print(cov_matrix)

[[2.213e+02 2.510e+05 3.340e+01]
 [2.510e+05 2.950e+08 3.800e+04]
 [3.340e+01 3.800e+04 5.200e+00]]

In [7]:
#Q6
'''You are working on a machine learning project with a dataset containing several categorical
variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD),
and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for
each variable, and why?


for gender category we will prefer using Labelencoder because there's no relationship between categories
for Education level we will use OrdinalEncoding because there's a relation between education level
for employment status we will use OneHotEncoding because so model do not assume any order between them

'''

'You are working on a machine learning project with a dataset containing several categorical\nvariables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor\'s/Master\'s/PhD),\nand "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for\neach variable, and why?\n\n\nfor gender category we will prefer using Labelencoder because there\'s no relationship between categories\nfor Education level we will use OrdinalEncoding because there\'s a relation between education level\nfor employment status we will use OneHotEncoding because so model do not assume any order between them\n\n'

In [8]:
#Q7
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
data = {
    'Temperature': [22, 24, 19, 23, 25, 21],
    'Humidity': [30, 45, 55, 60, 35, 50],
    'Weather Condition': ['Sunny', 'Cloudy', 'Rainy', 'Sunny', 'Cloudy', 'Rainy'],
    'Wind Direction': ['North', 'South', 'East', 'West', 'North', 'East']
}

df = pd.DataFrame(data)
OHE = OneHotEncoder()
weencoded = OHE.fit_transform(df[['Weather Condition']])
wetherdf= pd.DataFrame(weencoded.toarray(), columns=OHE.get_feature_names_out(['Weather Condition'] ) )
wiencoded = OHE.fit_transform(df[['Wind Direction']])
witherdf= pd.DataFrame(wiencoded.toarray(), columns=OHE.get_feature_names_out(['Wind Direction'] ) )
con_df = pd.concat([wetherdf,witherdf],axis=False )
con_df
final_df = pd.concat([df,con_df],axis=False).drop(columns=[ 'Weather Condition','Wind Direction'])
final_df

,Temperature,Humidity,Weather Condition_Cloudy,Weather Condition_Rainy,Weather Condition_Sunny,Wind Direction_East,Wind Direction_North,Wind Direction_South,Wind Direction_West
0,22.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,24.0,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,19.0,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,25.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,21.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,0.0,0.0,1.0,NaN,NaN,NaN,NaN
1,NaN,NaN,1.0,0.0,0.0,NaN,NaN,NaN,NaN
2,NaN,NaN,0.0,1.0,0.0,NaN,NaN,NaN,NaN
3,NaN,NaN,0.0,0.0,1.0,NaN,NaN,NaN,NaN
4,NaN,NaN,1.0,0.0,0.0,NaN,NaN,NaN,NaN
5,NaN,NaN,0.0,1.0,0.0,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0
1,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0
2,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0
3,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0
4,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0
5,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0